/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import napakalaki.Prize;

/**
 *
 * @author jose
 */
public class PrizeView extends javax.swing.JPanel {
    private Prize prizeModel;

    /** Creates new form PrizeView */
    public PrizeView() {
        initComponents();
    }
    
    public void setPrize (Prize aPrize) {
        // se actualiza el atributo de referencia
        prizeModel = aPrize;
        // se actualiza la vista del tesoro, por ejemplo
        this.jTexttesoros.setText (Integer.toString(prizeModel.getTreasures()));
        this.jTextniveles.setText (Integer.toString(prizeModel.getLevel()));
        // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTexttesoros = new javax.swing.JTextField();
        jTextniveles = new javax.swing.JTextField();

        jLabel1.setText("Tesoros ganados:");

        jLabel2.setText("Niveles Ganados:");

        jTexttesoros.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTexttesoros.setEnabled(false);

        jTextniveles.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextniveles.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextniveles)
                    .addComponent(jTexttesoros, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTexttesoros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextniveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextniveles;
    private javax.swing.JTextField jTexttesoros;
    // End of variables declaration//GEN-END:variables

}
